sudo: false
language: objective-c
xcode_project: Link.xcodeproj
xcode_scheme: Link

# http://stackoverflow.com/questions/27671854
script:
  - xctool -scheme Link clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
